model_selection:
    model:
      XGBClassifier:
        search_param_grid:
          max_depth: 
           - 3
           - 5
           - 7
           - 9
           - 11
          n_estimators:
           - 50
           - 100
           - 130
          random_state:
            - 0
            - 50
            - 100

          
      GaussianNB:
        search_param_grid:
          var_smoothing:
            - 0.5
            - 0.05
            - 0.01
